/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as WorklistRouteImport } from './routes/worklist'
import { Route as PatientIdRouteImport } from './routes/patient.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const WorklistRoute = WorklistRouteImport.update({
  id: '/worklist',
  path: '/worklist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinician': typeof ClinicianRoute
  '/connect': typeof ConnectRoute
  '/overview': typeof OverviewRoute
  '/worklist': typeof WorklistRoute
  '/patient/$id': typeof PatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinician': typeof ClinicianRoute
  '/connect': typeof ConnectRoute
  '/overview': typeof OverviewRoute
  '/worklist': typeof WorklistRoute
  '/patient/$id': typeof PatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinician': typeof ClinicianRoute
  '/connect': typeof ConnectRoute
  '/overview': typeof OverviewRoute
  '/worklist': typeof WorklistRoute
  '/patient/$id': typeof PatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clinician' | '/connect' | '/overview' | '/worklist' | '/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/clinician' | '/connect' | '/overview' | '/worklist' | '/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/clinician'
    | '/connect'
    | '/overview'
    | '/worklist'
    | '/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicianRoute: typeof ClinicianRoute
  ConnectRoute: typeof ConnectRoute
  OverviewRoute: typeof OverviewRoute
  WorklistRoute: typeof WorklistRoute
  PatientIdRoute: typeof PatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worklist': {
      id: '/worklist'
      path: '/worklist'
      fullPath: '/worklist'
      preLoaderRoute: typeof WorklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicianRoute: ClinicianRoute,
  ConnectRoute: ConnectRoute,
  OverviewRoute: OverviewRoute,
  WorklistRoute: WorklistRoute,
  PatientIdRoute: PatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
