"""
Data models for the patient journal backend.
Handles wearable metrics and AI interview data.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


# ============================================================================
# Wearable Data Models
# ============================================================================

class WearableMetricBase(BaseModel):
    """Base model for any wearable metric."""
    id: str
    subject_id: str
    record_date: str
    metric_type: str
    fetched_at: Optional[str] = None


class HeartRateData(BaseModel):
    """Heart rate metric data structure."""
    calendarDate: Optional[str] = None
    maxHeartRate: Optional[int] = None
    minHeartRate: Optional[int] = None
    userProfilePK: Optional[int] = None
    endTimestampGMT: Optional[str] = None
    heartRateValues: list[list[Optional[int]]] = Field(default_factory=list)
    restingHeartRate: Optional[int] = None
    endTimestampLocal: Optional[str] = None
    startTimestampGMT: Optional[str] = None
    startTimestampLocal: Optional[str] = None
    lastSevenDaysAvgRestingHeartRate: Optional[int] = None
    heartRateValueDescriptors: Optional[list[dict[str, Any]]] = None


class WearableMetric(WearableMetricBase):
    """Full wearable metric with typed data."""
    data: HeartRateData | dict[str, Any]


class WearablePayload(BaseModel):
    """Payload for POST /wearable endpoint - single or multiple metrics."""
    metrics: list[WearableMetric] = Field(
        ..., 
        description="List of wearable metrics (heart_rate for MVP)"
    )


# ============================================================================
# Interview Data Models
# ============================================================================

class TranscriptEntry(BaseModel):
    """Single entry in interview transcript."""
    role: str
    text: str
    ts: str


class InterviewField(BaseModel):
    """Structured field from AI interview."""
    id: str
    checkin_id: str
    field: str
    value: Any
    status: str
    evidence: str
    attempts: int


class InterviewData(BaseModel):
    """Full AI interview data."""
    id: str
    patient_id: str
    started_at: str
    ended_at: str
    status: str
    respondent: str
    summary: str
    transcript: list[TranscriptEntry] = Field(default_factory=list)
    fields: list[InterviewField] = Field(default_factory=list)
    alerts: list[dict[str, Any]] = Field(default_factory=list)


# ============================================================================
# Alert Models
# ============================================================================

class AlertSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    IMMEDIATE = "immediate"


class Alert(BaseModel):
    """Alert generated by the backend."""
    patient_id: str
    generated_at: datetime
    alert_type: str
    severity: AlertSeverity
    message: str
    source_metric: Optional[str] = None
    source_value: Optional[float] = None
    context: dict[str, Any] = Field(default_factory=dict)

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


# ============================================================================
# Internal Processing Models
# ============================================================================

class HeartRateReading(BaseModel):
    """Simplified heart rate reading for processing."""
    timestamp_ms: int
    value: float
    
    @classmethod
    def from_wearable(cls, timestamp_ms: int, value: Optional[int]) -> Optional["HeartRateReading"]:
        """Create from wearable data, filtering out nulls."""
        if value is None:
            return None
        return cls(timestamp_ms=timestamp_ms, value=float(value))
